### ISSUE TITLE
Unable to install this package in Mac M1-chip system

### ISSUE THREAD

**Issue by hqyida123** [ahoundetoungan/PartialNetwork#3]
Hi,

Thank you so much for making this package publicly available! I really like the paper and find it super clear, super useful, and super insightful! However, I encountered the following error message when trying to install the package on my MacBook:

Error: Failed to install 'PartialNetwork' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E>                   ~~~~~~^
E> remnonFinite.cpp:31:27: error: no member named 'find_nan' in namespace 'arma'
E>     tp            = arma::find_nan(out);
E>                     ~~~~~~^
E> 2 errors generated.
E> make: *** [remnonFinite.o] Error 1
E> ERROR: compilation failed for package ‘PartialNetwork’
E> * removing ‘/private/var/folders/41/crt9459553qfsh3sw1xmp2k00000gn/T/RtmpANiTKH/Rinst5d74c5c2e4b/PartialNetwork’
E>       -----------------------------------
E> ERROR: package installation failed

Could you point me to some clues to resolve this? Thanks a lot!"

**Comment by ahoundetoungan** [comment]
Hi,
Thanks for opening this issue. Can you tell me which version of R do you have?
Have you installed all the dependencies?
Imports: **Rcpp (>= 1.0.0), Formula, formula.tools, abind, Matrix, parallel, doParallel, foreach, doRNG**
LinkingTo: **Rcpp, RcppArmadillo, RcppEigen, RcppNumerical, RcppProgress**

**Comment by hqyida123** [comment]
The R version I have is 4.1.1 (2021-08-10), and I have checked I have installed all the dependencies you mentioned.

**Comment by ahoundetoungan** [comment]
The function `find_nan` is used in the latest version of the package. This function became accessible within Armadillo starting from Version 11.4. (see changes in this version here https://arma.sourceforge.net/docs.html#changelog). To access this version of Armadillo, you should have RcppArmadillo package version 0.11.4.4.0 (released on 2023-02-09). You can see here, https://cran.r-project.org/web/packages/RcppArmadillo/news.html, that `find_nan` is only available from this data.
Updating your R environment might not be necessary; instead, ensure that your RcppArmadillo package is at least version 0.11.4.4.0. 
Please let me know if this solution resolves your issue. Additionally, I've included this requirement in the package to enhance the clarity of error messages.

**Comment by hqyida123** [comment]
Thanks! I figured out the issue and have successfully installed the package! This webpage will be useful if someone has the similar issue: https://www.r-bloggers.com/2021/03/gfortran-support-for-r-on-macos/

**Comment by ahoundetoungan** [comment]
Great,
Don't hesitate to close the issue if it is solved.
